server:
  port: 7800
spring:
  application:
    name: sosospider
  data:
    elasticsearch:
      cluster-name: sosospider
      cluster-nodes: 39.108.106.39:9300
      local: true
      repositories:
        enabled: true