-- MySQL Script generated by MySQL Workbench
-- 04/10/19 14:53:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sosospider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sosospider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sosospider` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sosospider` ;

-- -----------------------------------------------------
-- Table `sosospider`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sosospider`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_account` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sosospider`.`web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sosospider`.`web` (
  `web_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `web_key` VARCHAR(1028) NULL,
  `web_addr` VARCHAR(256) NULL,
  `web_index` VARCHAR(128) NULL COMMENT '	',
  `web_time` VARCHAR(45) NULL,
  `web_auth` VARCHAR(45) NULL,
  PRIMARY KEY (`web_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sosospider`.`sys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sosospider`.`sys` (
  `sys_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sys_index_nums` VARCHAR(60) NULL,
  `sys_len_queue` VARCHAR(45) NULL,
  `sys_task_num` VARCHAR(45) NULL,
  `sys_csupervene` VARCHAR(45) NULL,
  `sys_es_num` VARCHAR(45) NULL,
  `sys_spider_num` VARCHAR(45) NULL,
  PRIMARY KEY (`sys_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sosospider`.`spider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sosospider`.`spider` (
  `spider_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `spider_remark` VARCHAR(128) NULL,
  `spider_id` VARCHAR(128) NULL,
  `spider_port` VARCHAR(45) NULL,
  `spider_status` VARCHAR(45) NULL COMMENT '1是空闲状态2是爬取状态',
  `spider_url` VARCHAR(45) NULL,
  PRIMARY KEY (`spider_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sosospider`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sosospider`.`admin` (
  `admin_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_account` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(45) NOT NULL,
  `admin_name` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
